packer_builder_name: "debian"
guest_os_type: "debian13-64"
vm_name: "debian-13"

preseed_config:
  mirror_hostname: "deb.debian.org"

iso_config:
  url: "https://cdimage.debian.org/debian-cd/current/amd64/iso-cd" 
  file: "debian-13.3.0-amd64-netinst.iso"
  checksum: "file:https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/SHA512SUMS"

boot_command:
  - "<wait3>c<wait3>"
  - "linux /install.amd/vmlinuz "
  - "auto-install/enable=true " 
  - "preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg "
  - "netcfg/hostname=debian netcfg/get_hostname=debian netcfg/get_domain='' "
  - "ipv6.disable=1 vga=788 noprompt quiet --<enter>" 
  - "initrd /install.amd/initrd.gz<enter>"
  - "boot<enter>"

installer: "preseed"
installer_files:
  - preseed.cfg